

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: DocsApp
      POSTGRES_USER: Gleb
      POSTGRES_PASSWORD: Gleb01012003
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  java-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: DocsApp
      DB_USER: Gleb
      DB_PASSWORD: Gleb01012003
    networks:
      - mynetwork


volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
